<?php

use Illuminate\Database\Seeder;

class DepartmentTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $departments = array(
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'กรุงเทพมหานคร', 'phase' => '1', 'phase_code' => 'DOL1 (DOL-11M-08)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'กทม.ดอนเมือง', 'phase' => '1', 'phase_code' => 'DOL1 (DOL-11M-08)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'กทม.พระโขนง', 'phase' => '1', 'phase_code' => 'DOL1 (DOL-11M-08)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'กทม.บางกะปิ', 'phase' => '1', 'phase_code' => 'DOL1 (DOL-11M-08)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'กทม.มีนบุรี', 'phase' => '1', 'phase_code' => 'DOL1 (DOL-11M-08)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'กทม.บางขุนเทียน', 'phase' => '1', 'phase_code' => 'DOL1 (DOL-11M-08)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'กทม.บางกอกน้อย', 'phase' => '1', 'phase_code' => 'DOL1 (DOL-11M-08)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'กทม.ธนบุรี', 'phase' => '1', 'phase_code' => 'DOL1 (DOL-11M-08)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'กทม.ห้วยขวาง', 'phase' => '1', 'phase_code' => 'DOL1 (DOL-11M-08)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'กทม.หนองแขม', 'phase' => '1', 'phase_code' => 'DOL1 (DOL-11M-08)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'กทม.ลาดพร้าว', 'phase' => '1', 'phase_code' => 'DOL1 (DOL-11M-08)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'กทม.ประเวศ', 'phase' => '1', 'phase_code' => 'DOL1 (DOL-11M-08)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'กทม.บึงกุ่ม', 'phase' => '1', 'phase_code' => 'DOL1 (DOL-11M-08)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'กทม.หนองจอก', 'phase' => '1', 'phase_code' => 'DOL1 (DOL-11M-08)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'กทม.ลาดกระบัง', 'phase' => '1', 'phase_code' => 'DOL1 (DOL-11M-08)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'กทม.บางเขน', 'phase' => '1', 'phase_code' => 'DOL1 (DOL-11M-08)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'สมุทรปราการ', 'phase' => '1', 'phase_code' => 'DOL1 (DOL-11M-08)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'สมุทรปราการ บางพลี', 'phase' => '1', 'phase_code' => 'DOL1 (DOL-11M-08)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'นครราชสีมา', 'phase' => '1', 'phase_code' => 'DOL1 (DOL-11M-08)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'สุรินทร์', 'phase' => '1', 'phase_code' => 'DOL1 (DOL-11M-08)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'นนทบุรี', 'phase' => '1', 'phase_code' => 'DOL1 (DOL-11M-08)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'นนทบุรี บางใหญ่', 'phase' => '1', 'phase_code' => 'DOL1 (DOL-11M-08)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'นนทบุรี ปากเกร็ด', 'phase' => '1', 'phase_code' => 'DOL1 (DOL-11M-08)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'นนทุบรี บางบัวทอง', 'phase' => '1', 'phase_code' => 'DOL1 (DOL-11M-08)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'ปทุมธานี', 'phase' => '1', 'phase_code' => 'DOL1 (DOL-11M-08)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'ปทุมธานี ลำลูกกา', 'phase' => '1', 'phase_code' => 'DOL1 (DOL-11M-08)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'ปทุมธานี ธัญบุรี', 'phase' => '1', 'phase_code' => 'DOL1 (DOL-11M-08)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'พระนครศรีอยุธยา', 'phase' => '1', 'phase_code' => 'DOL1 (DOL-11M-08)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'ลพบุรี', 'phase' => '1', 'phase_code' => 'DOL1 (DOL-11M-08)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'สระบุรี', 'phase' => '1', 'phase_code' => 'DOL1 (DOL-11M-08)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'ชลบุรี', 'phase' => '1', 'phase_code' => 'DOL1 (DOL-11M-08)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'ชลบุรี บางละมุง', 'phase' => '1', 'phase_code' => 'DOL1 (DOL-11M-08)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'ชลบุรี ศรีราชา', 'phase' => '1', 'phase_code' => 'DOL1 (DOL-11M-08)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'ระยอง', 'phase' => '1', 'phase_code' => 'DOL1 (DOL-11M-08)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'จันทบุรี', 'phase' => '1', 'phase_code' => 'DOL1 (DOL-11M-08)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'ฉะเชิงเทรา', 'phase' => '1', 'phase_code' => 'DOL1 (DOL-11M-08)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'ลำพูน', 'phase' => '1', 'phase_code' => 'DOL1 (DOL-11M-08)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'ลำปาง', 'phase' => '1', 'phase_code' => 'DOL1 (DOL-11M-08)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'เชียงราย', 'phase' => '1', 'phase_code' => 'DOL1 (DOL-11M-08)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'สุพรรณบุรี', 'phase' => '1', 'phase_code' => 'DOL1 (DOL-11M-08)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'นครปฐม', 'phase' => '1', 'phase_code' => 'DOL1 (DOL-11M-08)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'สมุทรสาคร', 'phase' => '1', 'phase_code' => 'DOL1 (DOL-11M-08)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'เพชรบุรี', 'phase' => '1', 'phase_code' => 'DOL1 (DOL-11M-08)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'ร้อยเอ็ด', 'phase' => '1', 'phase_code' => 'DOL1 (DOL-11M-08)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'บุรีรัมย์', 'phase' => '1', 'phase_code' => 'DOL1 (DOL-11M-08)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'นครนายก', 'phase' => '1', 'phase_code' => 'DOL1 (DOL-11M-08)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'ชัยนาท', 'phase' => '1', 'phase_code' => 'DOL1 (DOL-11M-08)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'พิษณุโลก', 'phase' => '1', 'phase_code' => 'DOL1 (DOL-11M-08)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'อุดรธานี', 'phase' => '1', 'phase_code' => 'DOL1 (DOL-11M-08)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'ขอนแก่น', 'phase' => '1', 'phase_code' => 'DOL1 (DOL-11M-08)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'ภูเก็ต', 'phase' => '1', 'phase_code' => 'DOL1 (DOL-11M-08)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'หนองคาย', 'phase' => '1', 'phase_code' => 'DOL1 (DOL-11M-08)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'หนองคาย ท่าบ่อ', 'phase' => '1', 'phase_code' => 'DOL1 (DOL-11M-08)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'หนองคาย โพนพิสัย', 'phase' => '1', 'phase_code' => 'DOL1 (DOL-11M-08)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'บึงกาฬ', 'phase' => '1', 'phase_code' => 'DOL1 (DOL-11M-08)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'บึงกาฬ เซกา', 'phase' => '1', 'phase_code' => 'DOL1 (DOL-11M-08)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'อุบลราชธานี', 'phase' => '1', 'phase_code' => 'DOL1 (DOL-11M-08)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'อุบลราชธานี เขื่องใน', 'phase' => '1', 'phase_code' => 'DOL1 (DOL-11M-08)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'อุบลราชธานี วารินชำราบ', 'phase' => '1', 'phase_code' => 'DOL1 (DOL-11M-08)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'อุบลราชธานี เดชอุดม', 'phase' => '1', 'phase_code' => 'DOL1 (DOL-11M-08)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'อุบลราชธานี น้ำยืน', 'phase' => '1', 'phase_code' => 'DOL1 (DOL-11M-08)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'อุบลราชธานี ม่วงสามสิบ', 'phase' => '1', 'phase_code' => 'DOL1 (DOL-11M-08)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'อุบลราชธานี ตระการพืชผล', 'phase' => '1', 'phase_code' => 'DOL1 (DOL-11M-08)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'อุบลราชธานี ศรีเมืองใหม่', 'phase' => '1', 'phase_code' => 'DOL1 (DOL-11M-08)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'อุบลราชธานี พิบูลมังสาหาร', 'phase' => '1', 'phase_code' => 'DOL1 (DOL-11M-08)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'อุบลราชธานี เขมราฐ', 'phase' => '1', 'phase_code' => 'DOL1 (DOL-11M-08)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'สงขลา', 'phase' => '1', 'phase_code' => 'DOL1 (DOL-11M-08)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'สงขลา หาดใหญ่', 'phase' => '1', 'phase_code' => 'DOL1 (DOL-11M-08)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'เชียงใหม่', 'phase' => '1', 'phase_code' => 'DOL1 (DOL-11M-08)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'เชียงใหม่ พร้าว', 'phase' => '1', 'phase_code' => 'DOL1 (DOL-11M-08)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'นครราชสีมา สาขาโนนสูง', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'นครราชสีมา สาขาประทาย', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'นครราชสีมา สาขาชุมพวง', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'นครราชสีมา สาขาจักราช', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'นครราชสีมา สาขาบัวใหญ่', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'นครราชสีมา สาขาพิมาย', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'นครราชสีมา สาขาดง', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'นครราชสีมา สาขาขามสะแกแสง', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'นครราชสีมา สาขาปากช่อง', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'นครราชสีมา สาขาปักธงชัย', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'นครราชสีมา สาขาสูงเนิน', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'นครราชสีมา สาขาด่านขุนทด', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'นครราชสีมา สาขาโชคชัย', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'นครราชสีมา สาขาโนนไทย', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'นครราชสีมา สาขาสีคิ้ว', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'นครราชสีมา สาขาครบุรี', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'นครราชสีมา ส่วนแยกขามทะเลสอ', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'พิษณุโลก สาขาพรมพิราม', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'พิษณุโลก สาขาระกำ', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'พิษณุโลก สาขานครไทย', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'พิษณุโลก สาขาวังทอง', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'พิษณุโลก สาขาวัดโบสถ์', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'พิษณุโลก สาขากระทุ่ม', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'เชียงใหม่ สาขาหางดง', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'เชียงใหม่ สาขาสันกำแพง', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'เชียงใหม่ สาขาป่าตอง', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'เชียงใหม่ สาขา สารภี', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'เชียงใหม่ สาขาดอยสะเก็ด', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'เชียงใหม่ สาขาจอมทอง', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'เชียงใหม่ ส่วนแยกแม่แจ่ม', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'เชียงใหม่ สาขาสันทราย', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'เชียงใหม่ สาขาฝาง', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'เชียงใหม่ สาขาแม่ริม', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'เชียงใหม่ สาขาเชียงดาว', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'เชียงใหม่ ส่วนแยกสะเมิง', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'เชียงใหม่ สาขาแม่แตง', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'ลำพููน สาขาป่าชาง', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'ลำพูน สาขาบ้านโฮ่ง', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'ลำพูน ส่วนแยกบ้านธิ', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'ลำพูน สาขาลี้', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'ลำพูน สาขาแม่ทา', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'แม่ฮ่องสอน', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'แม่ฮ่องสอน สาขาแม่สะเรียง', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'แม่ฮ่องสอน สาขาปาย', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'ลำปาง สาขาแจ้ห่ม', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'ลำปาง สาขาวังเหนือ', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'ลำปาง สาขางาว', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'ลำปาง สาขาห้างฉัตร', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'ลำปาง สาขาแม่ทะ', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'ลำปาง สาขาสบปราบ', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'ลำปาง สาขาเกาะคา', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'ลำปาง สาขาเถิน', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'ลำปาง สาขาเสริมงาม', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'ลำปาง สาขาแม่พริก', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'เชียงราย สาขาแม่จัน', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'เชียงราย สาขาเวียงชัย', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'เชียงราย สาขาแม่สาย', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'เชียงราย สาขาเชียงของ', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'เชียงราย สาขาเชียงแสน', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'เชียงราย สาขาพาน', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'เชียงราย สาขาเทิง', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'เชียงราย สาขาเวียงป่าเป้า', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'เชียงราย ส่วนแยกพระยาเม็งราย', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'เชียงราย ส่วนแยกป่าแดด', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'เชียงราย ส่วนแยกแม่สรวย', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'แพร่', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'แพร่ สาขาร้องกวาง', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'แพร่ สาขาลอง', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'แพร่ สาขาสอง', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'แพร่ สาขาวังชิ้น', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'แพร่ สาขาสูงเม่น', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'อุตรดิตถ์', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'อุตรดิตถ์ สาขาตรอน', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'อุตรดิตถ์ สาขาพิชัย', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'อุตรดิตถ์ สาขาน้ำปาด', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'สุโขทัย สาขาศรีสัชนาลัย', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'สุโขทัย สาขาสวรรคโลก', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'สุโขทัย สาขาศรีสำโรง', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'สุโขทัย', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'สุโขทัย สาขากงไกรลาศ', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'กำแพงเพชร', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'กำแพงเพชร สาขาคลองขลุง', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'กำแพงเพชร สาขาขาณุวรลักษบุรี', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'ตาก สาขาแม่สอด', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'ตาก', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'ตาก สาขาสามเงา', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'เพชรบูรณ์', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'หนองบัวลำภู สาขาศรีบุญเรือง', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'หนองบัวลำภู', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'มุกดาหาร', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'มุกดาหาร สาขาคำชะอี', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'อำนาจเจริญ', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'อำนาจเจริญ สาขาแยกพนา', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'อำนาจเจริญ สาขาหัวตะพาน', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'พะเยา ', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'พะเยา สาขาแม่ใจ', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'พะเยา สาขาดอกคำใต้', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'พะเยา สาขาเชียงคำ', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'พะเยา สาขาจุน', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'พะเยา สาขาปง', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'พะเยา สาขาปง ส่วนแยกเชียงม่วง', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'น่าน', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'น่าน สาขาเวียงสา', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'น่าน สาขานาน้อย', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'น่าน ส่วนแยกเชียงกลาง', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'น่าน สาขาท่าวังผา', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'น่าน สาขาปัว', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'พิจิตร', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'พิจิตร ส่วนแยกสามง่าม', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'พิจิตร สาขาโพธิ์ประทับช้าง', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'พิจิตร สาขาตะพานหิน', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'พิจิตร สาขาบางมูลนาก', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'พิจิตร สาขาโพทะเล', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'ขอนแก่น สาขาหนองเรือ', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'ขอนแก่น สาขาภูเวียง', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'ขอนแก่น สาขาชุมแพ', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'ขอนแก่น สาขาสีชมพู', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'ขอนแก่น ส่วนแยกอุบลรัตน์', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'ขอนแก่น สาขาน้ำพอง', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'ขอนแก่น สาขากระนวน', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'ขอนแก่น สาขาบ้านฝาง', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'ขอนแก่น สาขาพระยืน', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'ขอนแก่น สาขามัญจาคีรี', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'ขอนแก่น สาขาบ้านไผ่', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'ขอนแก่น สาขาแวงน้อย', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'ขอนแก่น สาขาพล', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'ขอนแก่น สาขาหนองสองห้อง', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'ชัยภูมิ', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'ชัยภูมิ สาขาบ้านเขว้า', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'ชัยภูมิ สาขาจัตุรัส', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'ชัยภูมิ สาขาบำเหน็จณรงค์', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'ชัยภูมิ สาขาคอนสวรรค์', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'ชัยภูมิ สาขาแก้งคร้อ', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'ชัยภูมิ สาขาภูเขียว', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'ชัยภูมิ สาขาเกษตรสมบูรณ์', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'บุรีรัมย์ สาขาลำปลายมาศ', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'บุรีรัมย์ ส่วนแยกคูเมือง', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'บุรีรัมย์ สาขาสตึก', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'บุรีรัมย์ สาขาพุธไธสง', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'บุรีรัมย์ สาขานางรอง', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'บุรีรัมย์ ส่วนแยกละหานทราย', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'บุรีรัมย์ สาขาประโคนชัย', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'บุรีรัมย์ สาขากระสัง', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'สุรินทร์ สาขาปราสาท', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'สุรินทร์ สาขาสังขะ', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'สุรินทร์ สาขาศีขรภูมิ', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'สุรินทร์ ส่วนแยกสำโรงทาบ', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'สุรินทร์ สาขาจอมพระ', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'สุรินทร์ สาขารัตนบุรี', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'สุรินทร์ สาขาท่าตูม', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'สุรินทร์ สาขาชุมพลบุรี', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'ศรีสะเกษ', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'ศรีสะเกษ สาขากันนทรารมย์', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'ศรีสะเกษ สาขาอุทุมพรพิสัย', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'ศรีสะเกษ สาขาราษีไศล', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'ศรีสะเกษ สาขากันนทรลักษ์', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'ศรีสะเกษ สาขาขุนหาญ', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'ศรีสะเกษ สาขาขุขันธ์', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'ศรีสะเกษ สาขาปรางค์กู่', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'มหาสารคาม', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'มหาสารคาม สาขาบรบือ', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'มหาสารคาม สาขานาเชือก', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'มหาสารคาม สาขากันทรวิชัย', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'มหาสารคาม สาขาเชียงยืน', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'มหาสารคาม สาขาโกสุมพิสัย', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'มหาสารคาม สาขาวาปีปทุม', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'มหาสารคาม สาขาพยัคฆภูมิพิสัย', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'ร้อยเอ็ด สาขาปทุมรัตต์', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'ร้อยเอ็ด สาขาจตุรพักตรพิมาน', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'ร้อยเอ็ด สาขาเกษตรวิสัย', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'ร้อยเอ็ด สาขาธวัชบุรี', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'ร้อยเอ็ด สาขาเสลภูมิ', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'ร้อยเอ็ด สาขาโพนทอง', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'ร้อยเอ็ด สาขาอาจสามารถ', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'ร้อยเอ็ด สาขาสุวรรณภูมิ', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'ร้อยเอ็ด สาขาพนมไพร', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'กาฬสินธุ์', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'กาฬสินธุ์ สาขายางตลาด', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'กาฬสินธุ์ สาขาหนองกุงศรี', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'กาฬสินธุ์ สาขามลาไสย', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'กาฬสินธุ์ สาขากุฉินนารายณ์', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'กาฬสินธุ์ สาขาสมเด็จ', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'นครพนม', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'นครพนม สาขาเรณูนคร', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'นครพนม สาขาธาตุพนม', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'นครพนม สาขานาแก', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'นครพนม สาขาท่าอุเทน', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'นครพนม สาขาศรีสงคราม', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'นครพนม ส่วนแยกนาหว้า', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'นครพนม ส่วนแยกบ้านแพง', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'ยโสธร', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'ยโสธร ส่วนแยกกุดชุม', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'ยโสธร สาขาเลิงนกทา', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'ยโสธร สาขาคำเขื่อนแก้ว', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'ยโสธร สาขามหาชนะชัย', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'เลย', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'เลย สาขาวังสะพุง', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'เลย สาขาด่านซ้าย', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'เลย สาขาภูกระดึง', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'เลย สาขาเชียงคาน', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'อุดรธานี สาขากุดจับ', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'อุดรธานี สาขาบ้านผือ', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'อุดรธานี ส่วนแยกน้ำโสม', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'อุดรธานี สาขาวัวซอ', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'อุดรธานี สาขากุมภวาปี', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'อุดรธานี ส่วนแยกโนนสะอาด', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'อุดรธานี ส่วนแยกศรีธาตุ', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'อุดรธานี สาขาเพ็ญ', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'อุดรธานี สาขาบ้านดุง', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'อุดรธานี ส่วนแยกทุ่งฝน', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'อุดรธานี สาขาหนองหาน', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'สกลนคร', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'สกลนคร ส่วนแยกกุสุมาลย์', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'สกลนคร สาขาพรรณานิคม', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'สกลนคร สาขาอากาศอำนวย', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'สกลนคร สาขาวานรนิวาส', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'สกลนคร สาขาพังโคน', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'สกลนคร สาขาวาริชภูมิ', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'สกลนคร สาขาสว่างแดนดิน', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'สกลนคร ส่วนแยกบ้านม่วง', 'phase' => '2', 'phase_code' => 'DOL2 (DOL-14L-09)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'สงขลา สาขาหาดใหญ่ ส่วนแยกบางกล่ำ', 'phase' => '1', 'phase_code' => 'DOL1 (DOL-11M-08)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'ปทุมธานี สาขาคลองหลวง', 'phase' => '4', 'phase_code' => 'DOL4 (DOL-14S-15)'],
['created_at' => new DateTime, 'updated_at' => new DateTime, 'create_user_id' => 1, 'name' => 'กทม. จตุจักร', 'phase' => '4', 'phase_code' => 'DOL4 (DOL-14S-15)'],


        );
		
        DB::table('departments')->insert($departments);
    }
}
